apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager-webhook-safedns.fullname" . }}
  labels:
    app: {{ include "cert-manager-webhook-safedns.name" . }}
    chart: {{ include "cert-manager-webhook-safedns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}